### ISSUE TITLE
forum.rustplatz.de login

### ISSUE THREAD

**Issue by oli-obk** [rustplatz/rustplatz.github.io#1]
> Da wuerde ich den Hoster jetzt eigentlich gern nochmal was fuer sein Geld tun lassen... 

Ich kann mich seit ca 2-3 Monaten schon nichtmehr einloggen und hab daher nurnoch mitgelesen ;)

Ich nutze den github-login. Auf users.rust-lang.org funktioniert der einwandfrei.

**Comment by panicbit** [comment]
Die Fehlermeldung ist `redirect_uri_mismatch`, wenn ich das aus der URL richtig ablese.

**Comment by thomanski** [comment]
Ist ja ein Tnueller. Ueber github nehme ich an? Oder direkt?

**Comment by panicbit** [comment]
Github

**Comment by thomanski** [comment]
Also nach einem long hard look auf die Einstellungen hab ich mich gefragt, warum sowohl "Homepage URL" als auch "Authorization callback URL" als http und nicht https angegeben waren, hab beides geaendert und nun scheint's wieder zu gehen.

Aber ich kann mir nicht vorstellen, dass ich an den Settings in der naeheren Vergangenheit (< 12 Monate) rumgefummelt haette.

Koennt ihr mal checken bitte, ob's bei euch jetzt auch geht?

**Comment by panicbit** [comment]
Super, klappt!

thomanski <notifications@github.com> schrieb am Sa., 6. Mai 2017, 19:58:

**Comment by thomanski** [comment]
Schoen, dass es wieder geht.
